InfoGeek/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InfoGeek.Data;
using InfoGeek.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;

namespace InfoGeek.Controllers
{
    public class AdminController : Controller
    {
        public readonly MongoContext _mongoContext;

        public AdminController(MongoContext mongoContext)
        {
            _mongoContext = mongoContext;
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult Dashboard()
        {
            var stats = this._mongoContext.Stats.ToDictionary();

            //------------Data from database----------------
            ViewData["avgObjSize"] = stats["avgObjSize"];
            ViewData["dataSize"] = stats["dataSize"];
            ViewData["totalSize"] = stats["fsTotalSize"];

            //-----------Data from users--------------------

            //The average of number of post vs users.
            double userSubscriptions = (this._mongoContext.Users.AsQueryable().Select(u => u.Posts.Count()).Sum()*1.0) / (this._mongoContext.Users.AsQueryable().Count()*1.0); 
            ViewData["userSubscriptions"] = userSubscriptions;

            //The average of users that have curriculums.
            ObjectId objectIdNull = new ObjectId("000000000000000000000000");

            double usersWithCurriculums = (this._mongoContext.Users.Find(u => !u.Curriculum.Equals(objectIdNull)).Count() * 1.0) / (this._mongoContext.Users.AsQueryable().Count() * 1.0);
            ViewData["usersWithCurriculums"] = usersWithCurriculums;

            //The users that have at least 10% more posts that the average
            int postsAverage = this._mongoContext.Posts.AsQueryable().Count() / this._mongoContext.Users.AsQueryable().Count();
            var userIds = _mongoContext.Users.AsQueryable().Where(u => u.Posts.Count() > postsAverage).Select(u => u.Id).AsEnumerable();

            var filter = new FilterDefinitionBuilder<ApplicationUser>().In(x => x.ActorId, userIds);

            var actors = this._mongoContext.ApplicationUsers.Find(filter).ToEnumerable();


            //------------------Data from Enterprises------------------

            //Enterprises that have at least one job offer
            var job = _mongoContext.Enterprises.AsQueryable().Where(e => e.Jobs.Count() > 1).Select(e => e.Name).AsEnumerable();
            ViewData["enterprises"] = job;

            return View(actors);
        }
    }
}

InfoGeek/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InfoGeek.Data;
using InfoGeek.Models;
using InfoGeek.Models.JobViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;

namespace InfoGeek.Controllers
{
    public class JobController : Controller
    {
        private readonly MongoContext mongoContext;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ObjectId emptyId = new ObjectId("000000000000000000000000");

        public JobController(MongoContext mongoContext, UserManager<ApplicationUser> userManager)
        {
            this.mongoContext = mongoContext;
            this.userManager = userManager;
        }

        // GET: Job
        [Authorize(Roles = "USER")]
        public ActionResult Index()
        {
            var jobs = this.mongoContext.Jobs.AsQueryable().ToEnumerable();

            var categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();

            TempData["Categories"] = categories;

            return View(jobs);
        }

        [Authorize(Roles = "ENTERPRISE")]
        public ActionResult MyJobs()
        {
            var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

            var enterpise = this.mongoContext.Enterprises.Find(e => e.Id.Equals(applicationUser.ActorId)).First();

            var filter = new FilterDefinitionBuilder<Job>().In(x => x.Id, enterpise.Jobs);

            var jobs = this.mongoContext.Jobs.Find(filter).ToEnumerable();

            var categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();

            TempData["Categories"] = categories;

            return View(jobs);
        }

        [Authorize(Roles = "USER")]
        public ActionResult Jobs(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var enterprise = this.mongoContext.Enterprises.Find(e => e.Id.Equals(objectId)).First();

            var filter = new FilterDefinitionBuilder<Job>().In(j => j.Id, enterprise.Jobs);

            var jobs = this.mongoContext.Jobs.Find(filter).ToEnumerable();

            var categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();

            TempData["Categories"] = categories;

            return View("MyJobs", jobs);
        }

        // GET: Job/Details/5
        [HttpGet("job/details/{id}")]
        public ActionResult Details(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var job = this.mongoContext.Jobs.Find(f => f.Id.Equals(objectId)).First();

            var actor = this.userManager.GetUserAsync(HttpContext.User).Result;

            var user = this.mongoContext.Users.Find(u => u.Id.Equals(actor.ActorId)).First();

            TempData["Subscribed"] = user.Subscribes.Contains(objectId) || user.Curriculum.Equals(emptyId);

            return View(job);
        }

        [HttpGet("job/enterprise/details/{id}")]
        public ActionResult DetailsEnterprise(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var job = this.mongoContext.Jobs.Find(f => f.Id.Equals(objectId)).First();

            TempData["Subscribed"] = true;

            return View("Details", job);
        }

        // GET: Job/Create
        [Authorize(Roles = "ENTERPRISE")]
        public ActionResult Create()
        {
            var categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();

            TempData["Categories"] = categories;

            return View();
        }

        // POST: Job/Create
        [Authorize(Roles = "ENTERPRISE")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(JobViewModel jobViewModel)
        {
            IEnumerable<Category> categories;
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

                    var user = this.mongoContext.Enterprises.Find(f => f.Id.Equals(applicationUser.ActorId)).First();

                    ObjectId objectId = new ObjectId(jobViewModel.Category);

                    var category = this.mongoContext.Categories.Find(c => c.Id.Equals(objectId)).First();

                    Job job = new Job
                    {
                        Id = ObjectId.GenerateNewId(),
                        Title = jobViewModel.Title,
                        Description = jobViewModel.Description,
                        Salary = jobViewModel.Salary,
                        Month = jobViewModel.Month,
                        Date = DateTime.Now,
                        Tags = jobViewModel.Tags.Split(","),
                        Category = category,
                        Curriculums = new List<ObjectId>()
                    };
                    user.Jobs.Add(job.Id);

                    this.mongoContext.Jobs.InsertOne(job);

                    UpdateDefinition<Enterprise> updateDefinition = Builders<Enterprise>.Update.Set("Jobs", user.Jobs);

                    this.mongoContext.Enterprises.FindOneAndUpdate(f => f.Id.Equals(user.Id), updateDefinition);

                    return RedirectToAction(nameof(MyJobs));
                }
                catch
                {
                    categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();
                    TempData["Categories"] = categories;

                    return View();
                }
            }
            categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();
            TempData["Categories"] = categories;
            return View();
        }

        // GET: Job/Edit/5
        [Authorize(Roles = "ENTERPRISE")]
        public ActionResult Edit(string id)
        {
            var actor = this.userManager.GetUserAsync(HttpContext.User).Result;
            var enterprise = this.mongoContext.Enterprises.Find(u => u.Id.Equals(actor.ActorId)).First();

            ObjectId objectId = new ObjectId(id);

            if (!enterprise.Jobs.Contains(objectId))
            {
                TempData["ErrorMessage"] = "You can't do this action.";
                return RedirectToAction(nameof(Index));
            }

            var job = this.mongoContext.Jobs.Find(j => j.Id.Equals(objectId)).First();

            JobViewModel jobViewModel = new JobViewModel
            {
                Title = job.Title,
                Description = job.Description,
                Salary = job.Salary,
                Tags = string.Join(",", job.Tags.ToArray()),
                Category = job.Category.Id.ToString(),
                Month = job.Month
            };

            var categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();

            TempData["Categories"] = categories;

            return View(jobViewModel);
        }

        // POST: Job/Edit/5
        [Authorize(Roles = "ENTERPRISE")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, JobViewModel jobViewModel)
        {
            IEnumerable<Category> categories;
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here

                    var actor = this.userManager.GetUserAsync(HttpContext.User).Result;
                    var enterprise = this.mongoContext.Enterprises.Find(u => u.Id.Equals(actor.ActorId)).First();

                    ObjectId objectId = new ObjectId(id);
                    ObjectId categoryId = new ObjectId(jobViewModel.Category);

                    if (!enterprise.Jobs.Contains(objectId))
                    {
                        TempData["ErrorMessage"] = "You can't do this action.";
                        return RedirectToAction(nameof(Index));
                    }

                    var category = this.mongoContext.Categories.Find(f => f.Id.Equals(categoryId)).First();

                    UpdateDefinition<Job> updateDefinition = Builders<Job>.Update.Set("Title", jobViewModel.Title)
                        .Set(j => j.Description, jobViewModel.Description)
                        .Set(j => j.Salary, jobViewModel.Salary)
                        .Set(j => j.Tags, jobViewModel.Tags.Split(","))
                        .Set(j => j.Category, category)
                        .Set(j => j.Month, jobViewModel.Month);

                    this.mongoContext.Jobs.FindOneAndUpdate(j => j.Id.Equals(objectId), updateDefinition);

                    return RedirectToAction(nameof(MyJobs));
                }
                catch
                {
                    categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();
                    TempData["Categories"] = categories;

                    return View(jobViewModel);
                }
            }
            categories = this.mongoContext.Categories.AsQueryable().ToEnumerable();
            TempData["Categories"] = categories;
            return View(jobViewModel);
        }

        // GET: Job/Delete/5
        [Authorize(Roles = "ENTERPRISE")]
        public ActionResult Delete(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

            var enterprise = this.mongoContext.Enterprises.Find(e => e.Id.Equals(applicationUser.ActorId)).First();

            if (!enterprise.Jobs.Contains(objectId))
            {
                TempData["ErrorMessage"] = "You can't do this action.";
                return RedirectToAction(nameof(Index));
            }
            enterprise.Jobs.Remove(objectId);

InfoGeek/Views/Shared/_Layout.cshtml
@inject InfoGeek.Services.SponsorShipChooser SponsorShipChooser

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InfoGeek</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Enterprise" asp-action="Index" class="navbar-brand">InfoGeek</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Folder" asp-action="Index">Folders</a></li>
                        
                    }
                    @if (User.IsInRole("ADMIN"))
                    {
                        <li><a asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                        <li><a asp-area="" asp-controller="SponsorShip" asp-action="Index">SponsorShips</a></li>
                        <li><a asp-area="" asp-controller="Admin" asp-action="Dashboard">Dashboard</a></li>
                    }
                    @if (User.IsInRole("USER"))
                    {
                        <li><a asp-area="" asp-controller="Job" asp-action="Index">Offers</a></li>
                        <li><a asp-area="" asp-controller="Post" asp-action="Index">Posts</a></li>
                        <li><a asp-area="" asp-controller="Post" asp-action="MyPosts">My Posts</a></li>
                        <li><a asp-area="" asp-controller="Curriculum" asp-action="Index">Curriculum</a></li>
                    }
                    @if (User.IsInRole("SPONSOR"))
                    {
                        <li><a asp-area="" asp-controller="SponsorShip" asp-action="MySponsorShips">SponsorShips</a></li>
                    }
                    @if (User.IsInRole("ENTERPRISE"))
                    {
                        <li><a asp-area="" asp-controller="Job" asp-action="MyJobs">My offers</a></li>

                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <div class="left">
            <p class="left">Sponsor by:</p><br />
            <img src="@SponsorShipChooser.ChooseSponsorShip()" class="img-responsive" width="400" height="400"/>
        </div>
        <hr />
        <footer>
            <p>&copy; 2018 - InfoGeek</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>