InfoGeek/Models/Curriculum.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InfoGeek.Models
{
    public class Curriculum
    {
        [BsonId]
        public ObjectId Id { get; set; }

        [BsonElement("Name")]
        [BsonRequired]
        public string Name { get; set; }

        [BsonElement("Surname")]
        [BsonRequired]
        public string Surname { get; set; }

        [BsonElement("Titles")]
        public ICollection<string> Titles { get; set; }

        [BsonElement("Knowledges")]
        public ICollection<string> Knowledges { get; set; }
    }
}

InfoGeek/Models/Job.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InfoGeek.Models
{
    public class Job
    {
        [BsonId]
        public ObjectId Id { get; set; }

        [BsonElement("Title")]
        [BsonRequired]
        public string Title { get; set; }

        [BsonElement("Description")]
        [BsonRequired]
        public string Description { get; set; }

        [BsonElement("Salary")]
        [Range(0, Double.MaxValue)]
        public double Salary { get; set; }

        [BsonElement("Month")]
        [BsonRequired]
        public bool Month { get; set; }

        [BsonElement("Date")]
        [BsonRequired]
        public DateTime Date { get; set; }

        [BsonElement("Tags")]
        [BsonRequired]
        public ICollection<String> Tags { get; set; }

        [BsonElement("Category")]
        [BsonRequired]
        public Category Category { get; set; }

        [BsonElement("Curriculums")]
        [BsonRequired]
        public ICollection<ObjectId> Curriculums { get; set; } 
    }
}

InfoGeek/Models/JobViewModels/JobViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InfoGeek.Models.JobViewModels
{
    public class JobViewModel
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Range(0, Double.MaxValue)]
        public double Salary { get; set; }
        
        [Required]
        public bool Month { get; set; }

        [Required]
        public string Tags { get; set; }

        [Required]
        public string Category { get; set; }
    }
}

InfoGeek/Models/PostViewModels/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InfoGeek.Models.PostViewModels
{
    public class CreateViewModel
    {
        [Required]
        public string Description { get; set; }

        [Required]
        [Url]
        public string Photo { get; set; }

        [Required]
        [Url]
        public string Url { get; set; }
    }
}

InfoGeek/Controllers/CurriculumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InfoGeek.Data;
using InfoGeek.Models;
using InfoGeek.Models.CurriculumViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;

namespace InfoGeek.Controllers
{
    public class CurriculumController : Controller
    {
        private readonly MongoContext mongoContext;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ObjectId emptyId = new ObjectId("000000000000000000000000");

        public CurriculumController(MongoContext mongoContext, UserManager<ApplicationUser> userManager)
        {
            this.mongoContext = mongoContext;
            this.userManager = userManager;
        }

        // GET: Curriculum
        [Authorize(Roles = "USER")]
        public ActionResult Index()
        {
            var user = this.userManager.GetUserAsync(HttpContext.User).Result;

            var curriculumId = this.mongoContext.Users.Find(u => u.Id.Equals(user.ActorId)).First().Curriculum;

            if (curriculumId.Equals(this.emptyId))
            {
                TempData["Empty"] = "true";
                return View();
            }

            TempData["Empty"] = "false";

            var curriculum = this.mongoContext.Curriculums.Find(c => c.Id.Equals(curriculumId)).First();

            return View(curriculum);
        }

        [Authorize(Roles = "USER, ENTERPRISE")]
        public ActionResult Details(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var curriculum = this.mongoContext.Curriculums.Find(c => c.Id.Equals(objectId)).First();

            return View(curriculum);
        }

        // GET: Curriculum/Create
        [Authorize(Roles = "USER")]
        public ActionResult Create()
        {
            var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

            var user = this.mongoContext.Users.Find(u => u.Id.Equals(applicationUser.ActorId)).First();

            if (!user.Curriculum.Equals(this.emptyId))
            {
                TempData["ErrorMessage"] = "You have already a curriculum.";
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // POST: Curriculum/Create
        [Authorize(Roles = "USER")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCurriculumViewModel collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

                    var user = this.mongoContext.Users.Find(u => u.Id.Equals(applicationUser.ActorId)).First();

                    if (!user.Curriculum.Equals(this.emptyId))
                    {
                        TempData["Empty"] = "false";
                        TempData["ErrorMessage"] = "You have already a curriculum.";
                        return RedirectToAction(nameof(Index));
                    }

                    Curriculum curriculum = new Curriculum
                    {
                        Id = ObjectId.GenerateNewId(),
                        Name = collection.Name,
                        Surname = collection.Surname,
                        Titles = collection.Titles.Split(","),
                        Knowledges = collection.Knowledges.Split(",")
                    };

                    this.mongoContext.Curriculums.InsertOne(curriculum);

                    UpdateDefinition<User> updateDefinition = Builders<User>.Update.Set(u => u.Curriculum, curriculum.Id);
                    this.mongoContext.Users.FindOneAndUpdate(u => u.Id.Equals(user.Id), updateDefinition);

                    TempData["Empty"] = "false";

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View(collection);
        }

        // GET: Curriculum/Edit/5
        [Authorize(Roles = "USER")]
        public ActionResult Edit(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

            var user = this.mongoContext.Users.Find(u => u.Id.Equals(applicationUser.ActorId)).First();

            if (user.Curriculum.Equals(this.emptyId) || !user.Curriculum.Equals(objectId))
            {
                TempData["ErrorMessage"] = "You can't edit this curriculum.";
                return RedirectToAction(nameof(Index));
            }

            var curriculum = this.mongoContext.Curriculums.Find(c => c.Id.Equals(objectId)).First();

            var eCurriculum = new CreateCurriculumViewModel
            {
                Name = curriculum.Name,
                Surname = curriculum.Surname,
                Titles = string.Join(",", curriculum.Titles.ToArray()),
                Knowledges = string.Join(",", curriculum.Knowledges.ToArray())
            };

            return View(eCurriculum);
        }

        // POST: Curriculum/Edit/5
        [Authorize(Roles = "USER")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, CreateCurriculumViewModel collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here

                    ObjectId objectId = new ObjectId(id);

                    var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

                    var user = this.mongoContext.Users.Find(u => u.Id.Equals(applicationUser.ActorId)).First();

                    if (user.Curriculum.Equals(this.emptyId) || !user.Curriculum.Equals(objectId))
                    {
                        TempData["ErrorMessage"] = "You can't edit this curriculum.";
                        return RedirectToAction(nameof(Index));
                    }

                    UpdateDefinition<Curriculum> update = Builders<Curriculum>.Update.Set(c => c.Name, collection.Name)
                        .Set(c => c.Surname, collection.Surname)
                        .Set(c => c.Titles, collection.Titles.Split(","))
                        .Set(c => c.Knowledges, collection.Knowledges.Split(","));

                    this.mongoContext.Curriculums.FindOneAndUpdate(c => c.Id.Equals(objectId), update);

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        // GET: Curriculum/Delete/5
        [Authorize(Roles = "USER")]
        public ActionResult Delete(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

            var user = this.mongoContext.Users.Find(u => u.Id.Equals(applicationUser.ActorId)).First();

            if (!user.Curriculum.Equals(objectId))
            {
                TempData["ErrorMessage"] = "This curriculum it's not yours";
                return View(nameof(Index));
            }
            this.mongoContext.Curriculums.FindOneAndDelete(c => c.Id.Equals(objectId));

            UpdateDefinition<User> update = Builders<User>.Update.Set(u => u.Curriculum, this.emptyId)
                .Set(u => u.Subscribes, new List<ObjectId>());
            this.mongoContext.Users.FindOneAndUpdate(u => u.Id.Equals(user.Id), update);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public ActionResult Curriculums(string id)
        {
            ObjectId objectId = new ObjectId(id);

            var applicationUser = this.userManager.GetUserAsync(HttpContext.User).Result;

            var enterprise = this.mongoContext.Enterprises.Find(e => e.Id.Equals(applicationUser.ActorId)).First();

            if (!enterprise.Jobs.Contains(objectId))
            {
                TempData["Error"] = "Yoy don't have access to this offer.";
                return RedirectToAction(nameof(Index));
            }

            var job = this.mongoContext.Jobs.Find(j => j.Id.Equals(objectId)).First();

            var filter = new FilterDefinitionBuilder<Curriculum>().In(x => x.Id, job.Curriculums);

            var curriculums = this.mongoContext.Curriculums.Find(filter).ToEnumerable();

            TempData["Enterprise"] = id;

            return View(curriculums);
        }
    }
}

InfoGeek/Views/Job/Create.cshtml
@model InfoGeek.Models.JobViewModels.JobViewModel

@{
    ViewData["Title"] = "Create offer";
    IEnumerable<Category> categories = TempData["Categories"] as IEnumerable<Category>;
}

<h2>Create offer</h2>

<h4>JobViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            @Html.DropDownListFor(model => model.Category, categories.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }), new { @class = "form-control" })
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Month"/> @Html.DisplayNameFor(model => model.Month)
                    </label>
                </div>
            </div>
            <!--Html.DropDownListFor(model => model.Category, new SelectList(TempData["Categories"])-->
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MyJobs">Back to List</a>
</div>

InfoGeek/Views/Job/Curriculums.cshtml
@model IEnumerable<InfoGeek.Models.Curriculum>

@{
    ViewData["Title"] = "Curriculums";
}

<h2>Curriculums</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Surname)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

InfoGeek/Views/Job/Details.cshtml
@model InfoGeek.Models.Job

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>

    @if (TempData["Subscribed"].Equals(false))
    {
        @Html.ActionLink("Subscribe", "Subscribe", new { id = Model.Id });
        @Html.Raw(" |");
    }

    @if (User.IsInRole("ENTERPRISE"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
        @Html.Raw(" | ")
        <a asp-action="Curriculums" asp-controller="Curriculum" asp-area="" asp-route-id="@Model.Id">Curriculums</a>
        @Html.Raw(" | ")
        /*@Html.ActionLink("Curriculums", "Curriculums", new { id = Model.Id });
        @Html.Raw(" |");*/
    }


    <a asp-action="Index">Back to List</a>
</div>

InfoGeek/Views/Job/Edit.cshtml
@model InfoGeek.Models.JobViewModels.JobViewModel

@{
    ViewData["Title"] = "Edit offer";
    IEnumerable<Category> categories = TempData["Categories"] as IEnumerable<Category>;
}

<h2>Edit offer</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Month" /> @Html.DisplayNameFor(model => model.Month)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            @Html.DropDownListFor(model => model.Category, categories.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }), new { @class = "form-control" })
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MyJobs">Back to List</a>
</div>

InfoGeek/Views/Job/Index.cshtml
@model IEnumerable<InfoGeek.Models.Job>

@{
    ViewData["Title"] = "Offers";
    string errMessage = TempData["ErrorMessage"] as string;
    string success = TempData["Success"] as string;
    IEnumerable<Category> categories = TempData["Categories"] as IEnumerable<Category>;
}

@Html.Raw(ViewData["Stats"])

<h2>Offers</h2>
@if (User.IsInRole("ENTERPRISE"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<span class="text-danger">@TempData["ErrorMessage"]</span>
<span class="text-success">@TempData["Success"]</span>
<br />
<div class="col-sm">
    <form asp-action="Filter">
        <div class="col-sm-3">
            @Html.DropDownList("id", categories.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }), new { @class = "form-control" })
        </div>
        <div class="col-sm-3">
            <input type="submit" value="filter" class=" btn btn-default" />
        </div>
    </form>
    <form asp-action="Search">
        <p>
            <div class="col-sm-3">
                <input type="text" name="key" class="form-control" placeholder="Search" />
            </div>
            <div class="col-sm-2">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
            
        </p>
    </form>
</div>
<div class="col-sm-4">
    
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @if (User.IsInRole("ENTERPRISE"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id });
                        @Html.Raw(" | ");
                        @Html.ActionLink("Details", "DetailsEnterprise", new { id = item.Id });
                        @Html.Raw(" | ");
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id });
                    }
                    @if (User.IsInRole("USER"))
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.Id });
                    }

                </td>
            </tr>
        }
    </tbody>
</table>

InfoGeek/Views/Job/MyJobs.cshtml
@model IEnumerable<InfoGeek.Models.Job>

@{
    ViewData["Title"] = "My offers";
    IEnumerable<Category> categories = TempData["Categories"] as IEnumerable<Category>;
}

<h2>My offers</h2>

@if (User.IsInRole("ENTERPRISE"))
{
    @Html.ActionLink("Create new", "Create")

}
<br />
<div class="col-sm">
    <form asp-action="FilterEnterprise">
        <div class="col-sm-3">
            @Html.DropDownList("id", categories.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }), new { @class = "form-control" })
        </div>
        <div class="col-sm-3">
            <input type="submit" value="filter" class=" btn btn-default" />
        </div>
    </form>
    <form asp-action="SearchEnterprise">
        <p>
            <div class="col-sm-3">
                <input type="text" name="key" class="form-control" placeholder="Search" />
            </div>
            <div class="col-sm-2">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>

        </p>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Salary)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Month)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Month)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @if (User.IsInRole("ENTERPRISE"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id })
                    @Html.Raw(" | ")
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                    @Html.Raw(" | ")
                    @Html.ActionLink("Details", "DetailsEnterprise", new { id=item.Id })
                }
                @if (User.IsInRole("USER"))
                {
                    @Html.ActionLink("Details", "Details", new { id=item.Id })

                }
                
                
            </td>
        </tr>
}
    </tbody>
</table>